export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENT_PRICES = 'GET_INGREDIENT_PRICES';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const GET_ORDERS = 'GET_ORDERS';